FROM golang:1.25-alpine@sha256:5caaf1cca9dc351e13deafbc3879fd4754801acba8653fa9540cea125d01a71f AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o soc-shell ./cmd/soc-shell/

FROM alpine:3.20@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc
RUN apk add --no-cache ca-certificates tzdata \
    && addgroup -S vsp && adduser -S -u 1000 -G vsp vsp
WORKDIR /app
COPY --from=builder --chown=vsp:vsp /app/soc-shell .
COPY --chown=vsp:vsp static/ ./static/

# SEC: Drop privileges
USER vsp:vsp

EXPOSE 8922
CMD ["./soc-shell"]
