#!/usr/bin/env bash
# scripts/test-l60-fuzz-coverage.sh — fuzz corpus growth + mutation coverage.
#
# Meta-testing of the test suite itself. Three signals:
#
#   1. Fuzz corpus has SEEDS in every FuzzXxx — not running fuzzers
#      against empty corpora.
#   2. Fuzz corpus grew over the last N commits (testdata/fuzz/*).
#      Stagnant corpus = fuzzers haven't discovered new inputs.
#   3. Mutation-test pinning files exist for security-critical
#      packages (auth, crypto, audit). Without pinning tests,
#      mutations can survive and accuracy is unknown.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
. "$ROOT/scripts/lib/vsp-test.sh"

PASS_COUNT=0; FAIL_COUNT=0; SKIP_COUNT=0; FAIL_LOG=()

# ── 60.1 Every FuzzXxx has at least one seed corpus entry ────────────────

phase_open "60.1 Fuzz seeds present for every FuzzXxx target"

FUZZ_TARGETS=$(grep -rEn '^func Fuzz[A-Z][A-Za-z0-9_]*\(' \
  --include='*_test.go' \
  "$ROOT/internal/" "$ROOT/cmd/" 2>/dev/null \
  | grep -v '\.bak' \
  || true)

if [[ -z "$FUZZ_TARGETS" ]]; then
  _skip "60.1.0 fuzz targets present" "no FuzzXxx functions found"
else
  COUNT=$(echo "$FUZZ_TARGETS" | wc -l | tr -d ' ')
  _pass "60.1.0 $COUNT FuzzXxx target(s) discovered"

  # Check that each target's testdata/fuzz/<TargetName>/ directory
  # has at least one seed entry. Go convention: seeds live in
  # testdata/fuzz/FuzzXxx/<hash> (auto-generated by f.Add).
  EMPTY_CORPORA=()
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    file=${line%%:*}
    func_name=$(echo "$line" | grep -oE 'Fuzz[A-Z][A-Za-z0-9_]*')
    dir=$(dirname "$file")
    corpus_dir="$dir/testdata/fuzz/$func_name"
    # Source `f.Add(...)` calls count as seeds too (Go's go test
    # -fuzz puts those in the in-memory corpus before disk).
    if [[ -d "$corpus_dir" ]] && [[ -n "$(ls -A "$corpus_dir" 2>/dev/null)" ]]; then
      continue  # has disk seeds
    fi
    if grep -q "f\.Add(" "$file" 2>/dev/null; then
      continue  # has source-level f.Add
    fi
    EMPTY_CORPORA+=("$func_name in $(basename "$file")")
  done <<<"$FUZZ_TARGETS"

  if (( ${#EMPTY_CORPORA[@]} == 0 )); then
    _pass "60.1.1 every fuzz target has seed corpus (disk or f.Add)"
  else
    _fail "60.1.1 empty fuzz corpora" \
      "${EMPTY_CORPORA[0]} — fuzzer with no seeds runs blind"
  fi
fi

# ── 60.2 Fuzz corpus directory size sanity ───────────────────────────────

phase_open "60.2 Fuzz corpus on-disk volume"

CORPUS_BYTES=0
if find "$ROOT" -type d -path '*/testdata/fuzz/*' 2>/dev/null | head -1 >/dev/null; then
  CORPUS_BYTES=$(find "$ROOT" -type f -path '*/testdata/fuzz/*' \
    -not -path '*/.bak*' \
    -exec wc -c {} + 2>/dev/null | tail -1 | awk '{print $1}' || echo 0)
  CORPUS_BYTES=${CORPUS_BYTES:-0}
fi

# A healthy corpus accumulates over time. Threshold: ≥1KB total
# means at least a handful of crash-saved or growth inputs.
if (( CORPUS_BYTES >= 1024 )); then
  _pass "60.2.1 fuzz corpus on disk: $CORPUS_BYTES bytes"
elif (( CORPUS_BYTES == 0 )); then
  _skip "60.2.1 fuzz corpus" \
    "0 bytes — nightly fuzz hasn't run yet OR corpus is gitignored"
else
  _skip "60.2.1 fuzz corpus thin" \
    "$CORPUS_BYTES bytes — fuzzer ran but found few growth inputs"
fi

# ── 60.3 Mutation-test pinning files for critical packages ───────────────

phase_open "60.3 Mutation-pinning tests on auth + crypto + audit"

# Three packages are security-critical and must have mutation-aware
# tests. The L11 mutation runner (test-l11-mutation.sh) operates on
# these. Probe: each package has at least one *_test.go that asserts
# specific constants / branches (catches survived mutations).
CRITICAL_PKGS=("internal/auth" "internal/crypto" "internal/audit")
MISSING=()
for pkg in "${CRITICAL_PKGS[@]}"; do
  if [[ ! -d "$ROOT/$pkg" ]]; then
    continue  # package doesn't exist in this build
  fi
  # At least 2 *_test.go files = some test discipline. Less = thin.
  test_count=$(find "$ROOT/$pkg" -maxdepth 2 -name '*_test.go' 2>/dev/null | wc -l | tr -d ' ')
  if (( test_count < 2 )); then
    MISSING+=("$pkg ($test_count test files)")
  fi
done

if (( ${#MISSING[@]} == 0 )); then
  _pass "60.3.1 every critical package has ≥2 test files"
else
  _fail "60.3.1 critical package under-tested" "${MISSING[0]}"
fi

# 60.3.2 — verify the L11 mutation script targets these packages.
if [[ -r "$ROOT/scripts/test-l11-mutation.sh" ]]; then
  COVERED=0
  for pkg in "${CRITICAL_PKGS[@]}"; do
    if grep -q "$pkg" "$ROOT/scripts/test-l11-mutation.sh" 2>/dev/null; then
      COVERED=$((COVERED + 1))
    fi
  done
  if (( COVERED == ${#CRITICAL_PKGS[@]} )); then
    _pass "60.3.2 L11 mutation runner covers auth + crypto + audit"
  else
    _fail "60.3.2 L11 mutation coverage gap" \
      "$COVERED/${#CRITICAL_PKGS[@]} critical packages targeted by L11"
  fi
else
  _skip "60.3.2 L11 mutation coverage check" "test-l11-mutation.sh not readable"
fi

# ── 60.4 Fuzz dispatch budget present in workflow ────────────────────────

phase_open "60.4 CI workflow allocates fuzz budget"

# release-readiness.yml should expose FUZZTIME as a workflow input,
# so devs can extend fuzz time for a specific PR via dispatch.
WF="$ROOT/.github/workflows/release-readiness.yml"
if [[ -r "$WF" ]] && grep -qE 'fuzztime|FUZZTIME' "$WF"; then
  _pass "60.4.1 release-readiness.yml exposes fuzztime input"
else
  _skip "60.4.1 fuzz budget input" "no fuzztime input in workflow (informational)"
fi

final_summary
